name: build

on:
  push:
    paths:
      - src/**

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: set plugin version
        run: echo "version=$(./gradlew -q getVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: set mc version
        run: echo "version=$(./gradlew -q getMinecraftVersion)" >> $GITHUB_OUTPUT
        id: mc
      - name: capture 
        uses: actions/upload-artifact@v3
        with:
          name: UnQuitter-v${{steps.plugin.outputs.version}}-mc${{steps.mc.outputs.version}}-id$((github.run_id)).jar
          path: build/libs/*-${{steps.plugin.outputs.version}}.jar