name: build

on:
  push:
    tags-ignore:
      - v**

  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    concurrency: on_push
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name : set version
        run: echo "version=$(./gradlew -q getVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: get version
        run: echo "plugin_version=${{steps.plugin.outputs.version}}" >> $GITHUB_ENV
      - name: capture 
        uses: actions/upload-artifact@v3
        with:
          name: UnQuitter-${{env.plugin_version}}.jar
          path: build/libs/*-${{env.plugin_version}}.jar