# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: build
on: [ pull_request, push ]
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name : set version
        run: echo "version=$(./gradlew -q getVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: get version
        run: echo "plugin_version=${{steps.plugin.outputs.version}}" >> $GITHUB_ENV
      - name: capture 
        uses: actions/upload-artifact@v3
        with:
          name: UnQuitter-${{env.plugin_version}}.jar
          path: build/libs/*-${{env.plugin_version}}.jar
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: UnQuitter ${{env.plugin_version}}
          files: build/libs/*-${{env.plugin_version}}.jar
