name: release
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: set version
        run: echo "version=$(./gradlew -q getVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: set mc version
        run: echo "mc_version=$(./gradlew -q getMinecraftVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          name: UnQuitter v${{steps.plugin.outputs.version}} for Minecraft v${{steps.plugin.outputs.mc_version}}
          files: build/libs/*-v${{steps.plugin.outputs.version}}-mc${{steps.plugin.outputs.mc_version}}.jar