name: release
on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')
    concurrency: on_push
    steps:
      - name: "upload"
      uses: softprops/action-gh-release@v1
      with:
        name: UnQuitter ${{env.plugin_version}}
        files: build/libs/*-${{env.plugin_version}}.jar
