name: release
on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    concurrency: on_push
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: set version
        run: echo "version=$(./gradlew -q getVersion)" >> $GITHUB_OUTPUT
        id: plugin
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: UnQuitter-${{steps.plugin.outputs.version}}-run${{github.run_number-1}}.jar
      - name: rename artifact
        run: mv UnQuitter-${{steps.plugin.outputs.version}}-run${{github.run_number-1}}.jar UnQuitter-${{steps.plugin.outputs.version}}.jar
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          name: UnQuitter v${{steps.plugin.outputs.version}}
          files: UnQuitter-${{steps.plugin.outputs.version}}.jar