name: release
on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    concurrency: on_push
    steps:
      - name: build
      uses: ./.github/workflows/build.yml
      - name: upload
      uses: softprops/action-gh-release@v1
      with:
        name: UnQuitter ${{env.plugin_version}}
        files: build/libs/*-${{env.plugin_version}}.jar